baseURL: "https://Rayhaneh-Einollahi.github.io/" 
title: Rayhaneh Einollahi
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Experience
          url: experience/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Awards
          url: awards/
          weight: 3
        - name: Resume
          url: cv_rosa2.pdf
          weight: 4 
        - name: Beyond Code
          url: arts/
          weight: 5
        # - name: Photography
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am a Computer Engineering Student at University of Tehran."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Rayhaneh Einollahi
          subtitle: "I'm a Computer Engineering student at the University of Tehran, passionate about Compiler Design, Algorithms, and Graph Theory. <br>

            Currently, I'm working on the backend of a compiler for the SAYAC embedded system, focusing on intermediate representation (IR) design, instruction selection, and optimization passes. Alongside this, I'm exploring advanced topics in compiler construction and static program analysis.<br>
            
            My main interests lie in building and analyzing **complex algorithms**, **designing efficient language processing tools**, and applying **formal methods** to solve real-world problems.
            
            I'm eager to collaborate on projects where theory meets practiceâ€”especially those involving compiler development, algorithm engineering, or graph-theoretic approaches."
          imageUrl: "picture2.jpg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Rayhaneh Einollahi
          buttons:
            - name: Experience
              url: experience/
            - name: Projects
              url: projects/
            - name: Awards
              url: awards/
            - name: Resume
              url: cv_rosa2.pdf
            - name: Beyond Code
              url: arts/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
           # - name: Newsletter
           #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            # - name: Talks
            #   url: talks/
            # - name: Resume
            #   url: cv_rosa2.pdf
            #- name: Archive
            #  url: archive/
    socialIcons:
        # - name: CV
        #   url: cv_rosa.pdf
        - name: Email
          url: mailto:Rayhaneheinollahi@gmail.com
        - name: Location
          url: location/
    
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=jwrYE5sAAAAJ&hl=fr
        - name: LinkedIn
          url: https://linkedin.com/in/rayhaneh-einollahi
        - name: GitHub
          url: https://github.com/Rayhaneh-Einollahi
        # - name: ORCID
        #   url: https://orcid.org/0000-0002-9417-1075
      

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rayhaneh Einollahi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
